apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
    name: "disco1"
spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
        requests:
            storage: "1Mi"
        volumeName: "pv100"
