apiVersion: "v1"
kind: "Pod"
metadata:
    name: "httpd"
    labels:
        name: "ejemplo_httpd"
    spec:
	containers:
		-
		name: "httpd"
		image: httpd
		ports:
		-
			containerPort: 80
			name: "http-server"
		volumeMounts:
		-
			mountPath: "/var/www/html"
			name: "pvol"
		volumes:
		-
			name: "pvol"
			persistentVolumeClaim:
			claimName: "bbdd"