apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tomcat-d
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3 
  template:   
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: httpd
        ports:
        - containerPort: 8080

