apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: desa1
spec:
  selector:
    matchLabels:
      app: ejemplo-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: ejemplo-deploy
    spec:
      containers:
        - name: hello-openshift
          image: openshift/hello-openshift
          ports:
            - containerPort: 8080
