apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
spec:
  ports:
  - name: 8069-tcp
    port: 8069
    protocol: TCP
    targetPort: 8069
  - name: 8071-tcp
    port: 8071
    protocol: TCP
    targetPort: 8071
  - name: 8072-tcp
    port: 8072
    protocol: TCP
    targetPort: 8072
  selector:
    deploymentconfig: odoo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
