apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pythonapp
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: pythonapp:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/ApasoftTraining/python-app 
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: mi-imagen:v1
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: secret-webhook
    type: Generic
  - github:
      secretReference:
        name: secret-webhook
    type: GitHub
  - imageChange:
    type: ImageChange
  - type: ConfigChange
