apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-input
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: docker-input:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: "FROM centos:7\nCMD echo 'Hola, estas probando un dockerfile inline' && exec sleep infinity" 
    type: dockerfile
  strategy:
    dockerStrategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
