apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: binary
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: binary:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial 
  source:
    git:
      uri: https://github.com/ApasoftTraining/ejemplophp.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
